{
  "affected": [
    {
      "database_specific": {
        "source": "https://storage.googleapis.com/debian-osv/dla-osv/DLA-4301-1.json"
      },
      "package": {
        "ecosystem": "Debian:11",
        "name": "python-django",
        "purl": "pkg:deb/debian/python-django?arch=source"
      },
      "ranges": [
        {
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "2:2.2.28-1~deb11u8"
            }
          ],
          "type": "ECOSYSTEM"
        }
      ],
      "versions": [
        "2:2.2.24-1",
        "2:2.2.25-1~deb11u1",
        "2:2.2.26-1~deb11u1",
        "2:2.2.28-1~deb11u1",
        "2:2.2.28-1~deb11u2",
        "2:2.2.28-1~deb11u3",
        "2:2.2.28-1~deb11u4",
        "2:2.2.28-1~deb11u5",
        "2:2.2.28-1~deb11u6",
        "2:2.2.28-1~deb11u7"
      ]
    }
  ],
  "id": "DLA-4301-1",
  "modified": "2025-09-15T23:31:27.915223Z",
  "published": "2025-09-15T00:00:00Z",
  "schema_version": "1.7.3",
  "summary": "python-django - security update",
  "upstream": [
    "CVE-2025-57833"
  ]
}