{
  "affected": [
    {
      "database_specific": {
        "source": "https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2022/01/GHSA-756h-r2c9-qp5j/GHSA-756h-r2c9-qp5j.json"
      },
      "package": {
        "ecosystem": "PyPI",
        "name": "gerapy",
        "purl": "pkg:pypi/gerapy"
      },
      "ranges": [
        {
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "0.9.9"
            }
          ],
          "type": "ECOSYSTEM"
        }
      ],
      "versions": [
        "0.6.6",
        "0.6.7",
        "0.6.8",
        "0.6.9",
        "0.7.0",
        "0.7.1",
        "0.7.2",
        "0.7.3",
        "0.7.6",
        "0.7.7",
        "0.7.8",
        "0.7.9",
        "0.8.0",
        "0.8.1",
        "0.8.2",
        "0.8.3",
        "0.8.4rc2",
        "0.8.5",
        "0.8.5rc2",
        "0.8.6",
        "0.8.6a0",
        "0.8.6b0",
        "0.8.6b1",
        "0.8.6rc1",
        "0.8.6rc2",
        "0.8.7",
        "0.8.8",
        "0.9.0",
        "0.9.1",
        "0.9.2",
        "0.9.2a0",
        "0.9.2rc1",
        "0.9.3",
        "0.9.3a1",
        "0.9.3a2",
        "0.9.3b1",
        "0.9.5",
        "0.9.6",
        "0.9.6a1",
        "0.9.7",
        "0.9.8"
      ]
    }
  ],
  "aliases": [
    "CVE-2021-32849",
    "PYSEC-2022-17"
  ],
  "database_specific": {
    "cwe_ids": [
      "CWE-77",
      "CWE-78"
    ],
    "github_reviewed": true,
    "github_reviewed_at": "2022-01-06T23:30:47Z",
    "nvd_published_at": "2022-01-26T22:15:00Z",
    "severity": "HIGH"
  },
  "details": "### Impact\n\nAn authenticated user can execute arbitrary command, see more in https://github.com/Gerapy/Gerapy/issues/211.\n\n### Patches\n\nFixed in 0.9.9",
  "id": "GHSA-756h-r2c9-qp5j",
  "modified": "2024-09-20T20:25:25.167417Z",
  "published": "2022-01-06T23:48:50Z",
  "references": [
    {
      "type": "WEB",
      "url": "https://github.com/Gerapy/Gerapy/security/advisories/GHSA-756h-r2c9-qp5j"
    },
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2021-32849"
    },
    {
      "type": "WEB",
      "url": "https://github.com/Gerapy/Gerapy/issues/197"
    },
    {
      "type": "WEB",
      "url": "https://github.com/Gerapy/Gerapy/issues/217"
    },
    {
      "type": "WEB",
      "url": "https://github.com/Gerapy/Gerapy"
    },
    {
      "type": "WEB",
      "url": "https://github.com/pypa/advisory-database/tree/main/vulns/gerapy/PYSEC-2022-17.yaml"
    },
    {
      "type": "WEB",
      "url": "https://lgtm.com/projects/g/Gerapy/Gerapy?mode=tree&ruleFocus=1505994646253"
    },
    {
      "type": "ADVISORY",
      "url": "https://securitylab.github.com/advisories/GHSL-2021-076-gerapy"
    }
  ],
  "related": [
    "CVE-2021-32849"
  ],
  "schema_version": "1.7.3",
  "severity": [
    {
      "score": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H",
      "type": "CVSS_V3"
    },
    {
      "score": "CVSS:4.0/AV:N/AC:L/AT:N/PR:L/UI:N/VC:H/VI:H/VA:H/SC:N/SI:N/SA:N",
      "type": "CVSS_V4"
    }
  ],
  "summary": "An authenticated user can execute arbitrary command in Gerapy"
}