{
  "affected": [
    {
      "database_specific": {
        "source": "https://github.com/ossf/malicious-packages/blob/main/osv/malicious/pypi/asynctestpython/MAL-2025-2939.json"
      },
      "package": {
        "ecosystem": "PyPI",
        "name": "asynctestpython",
        "purl": "pkg:pypi/asynctestpython"
      },
      "versions": [
        "0.1"
      ]
    }
  ],
  "credits": [
    {
      "contact": [
        "https://www.reversinglabs.com"
      ],
      "name": "ReversingLabs",
      "type": "FINDER"
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "id": "RLMA-2025-01937",
        "import_time": "2025-03-31T07:07:04.697413601Z",
        "modified_time": "2025-03-28T13:05:21Z",
        "sha256": "929e7aac59882b3f73eae18de1a5e7777a84a4711f64e8fab23136014a349d73",
        "source": "reversing-labs",
        "versions": [
          "0.1"
        ]
      }
    ]
  },
  "details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
  "id": "MAL-2025-2939",
  "modified": "2025-03-28T13:05:21Z",
  "published": "2025-03-28T13:05:21Z",
  "schema_version": "1.7.0",
  "summary": "Malicious code in asynctestpython (PyPI)"
}