{
  "affected": [
    {
      "database_specific": {
        "source": "https://github.com/ossf/malicious-packages/blob/main/osv/malicious/pypi/certifii/MAL-2025-41632.json"
      },
      "package": {
        "ecosystem": "PyPI",
        "name": "certifii",
        "purl": "pkg:pypi/certifii"
      },
      "versions": [
        "2022.12.7"
      ]
    }
  ],
  "credits": [
    {
      "contact": [
        "https://www.reversinglabs.com"
      ],
      "name": "ReversingLabs",
      "type": "FINDER"
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "id": "RLMA-2025-04123",
        "import_time": "2025-08-29T06:41:39.377691569Z",
        "modified_time": "2025-08-28T07:10:44Z",
        "sha256": "bb9894e0bab1770bc41ac68cddcaeaa9efa02379c5433a24553e1d5dd1feb484",
        "source": "reversing-labs",
        "versions": [
          "2022.12.7"
        ]
      }
    ]
  },
  "details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
  "id": "MAL-2025-41632",
  "modified": "2025-08-28T07:10:44Z",
  "published": "2025-08-28T07:10:44Z",
  "schema_version": "1.7.3",
  "summary": "Malicious code in certifii (PyPI)"
}