{
  "affected": [
    {
      "database_specific": {
        "source": "https://github.com/ossf/malicious-packages/blob/main/osv/malicious/pypi/discordsync/MAL-2025-41662.json"
      },
      "package": {
        "ecosystem": "PyPI",
        "name": "discordsync",
        "purl": "pkg:pypi/discordsync"
      },
      "versions": [
        "1.3.0",
        "1.4.0"
      ]
    }
  ],
  "credits": [
    {
      "contact": [
        "https://www.reversinglabs.com"
      ],
      "name": "ReversingLabs",
      "type": "FINDER"
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "id": "RLMA-2025-04154",
        "import_time": "2025-08-29T06:41:42.794881001Z",
        "modified_time": "2025-08-28T07:10:59Z",
        "sha256": "08ddf71ec52dd716d82c33a7b5755a4589d3e822867de52684d8c560ef229035",
        "source": "reversing-labs",
        "versions": [
          "1.3.0",
          "1.4.0"
        ]
      }
    ]
  },
  "details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
  "id": "MAL-2025-41662",
  "modified": "2025-08-28T07:10:59Z",
  "published": "2025-08-28T07:10:59Z",
  "schema_version": "1.7.3",
  "summary": "Malicious code in discordsync (PyPI)"
}