{
  "affected": [
    {
      "database_specific": {
        "source": "https://advisories.mageia.org/MGASA-2022-0359.json"
      },
      "ecosystem_specific": {
        "section": "core"
      },
      "package": {
        "ecosystem": "Mageia:8",
        "name": "python3",
        "purl": "pkg:rpm/mageia/python3?arch=source&distro=mageia-8"
      },
      "ranges": [
        {
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "3.8.14-1.1.mga8"
            }
          ],
          "type": "ECOSYSTEM"
        }
      ],
      "versions": []
    },
    {
      "database_specific": {
        "source": "https://advisories.mageia.org/MGASA-2022-0359.json"
      },
      "ecosystem_specific": {
        "section": "core"
      },
      "package": {
        "ecosystem": "Mageia:8",
        "name": "python-pip",
        "purl": "pkg:rpm/mageia/python-pip?arch=source&distro=mageia-8"
      },
      "ranges": [
        {
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "22.0.4-1.mga8"
            }
          ],
          "type": "ECOSYSTEM"
        }
      ],
      "versions": []
    }
  ],
  "credits": [
    {
      "contact": [
        "https://wiki.mageia.org/en/Packages_Security_Team"
      ],
      "name": "Mageia",
      "type": "COORDINATOR"
    }
  ],
  "details": "Converting between int and str in bases other than 2 (binary), 4, 8\n(octal), 16 (hexadecimal), or 32 such as base 10 (decimal) now raises a\nValueError if the number of digits in string form is above a limit to\navoid potential denial of service attacks due to the algorithmic\ncomplexity. (CVE-2020-10735)\nmailcap module does not add escape characters into commands discovered in\nthe system mailcap file. This may allow attackers to inject shell commands\ninto applications that call mailcap.findmatch with untrusted input (if\nthey lack validation of user-provided filenames or arguments).\n(CVE-2015-20107)\nOpen redirection vulnerability in lib/http/server.py due to no protection\nagainst multiple (/) at the beginning of URI path which may leads to\ninformation disclosure. (CVE-2021-28861)\nAlso fixes permissions and title for the documentation.\n",
  "id": "MGASA-2022-0359",
  "modified": "2022-10-08T19:27:51Z",
  "published": "2022-10-08T20:22:22Z",
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://advisories.mageia.org/MGASA-2022-0359.html"
    },
    {
      "type": "REPORT",
      "url": "https://bugs.mageia.org/show_bug.cgi?id=30848"
    },
    {
      "type": "REPORT",
      "url": "https://bugs.mageia.org/show_bug.cgi?id=30929"
    },
    {
      "type": "REPORT",
      "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/thread/2VCU6EVQDIXNCEDJUCTFIER2WVNNDTYZ/"
    },
    {
      "type": "REPORT",
      "url": "https://pythoninsider.blogspot.com/2022/09/python-releases-3107-3914-3814-and-3714.html"
    },
    {
      "type": "REPORT",
      "url": "https://www.openwall.com/lists/oss-security/2022/09/21/1"
    },
    {
      "type": "REPORT",
      "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/thread/OKYE2DOI2X7WZXAWTQJZAXYIWM37HDCY/"
    },
    {
      "type": "REPORT",
      "url": "https://ubuntu.com/security/notices/USN-5629-1"
    },
    {
      "type": "REPORT",
      "url": "https://lists.opensuse.org/archives/list/security-announce@lists.opensuse.org/thread/LSVFIZF6ZYMLK2HRCPTYDPZM3P6NDQKU/"
    }
  ],
  "related": [
    "CVE-2015-20107",
    "CVE-2020-10735",
    "CVE-2021-28861"
  ],
  "schema_version": "1.6.0",
  "summary": "Updated python3 packages fix security vulnerability"
}