{
  "affected": [
    {
      "database_specific": {
        "source": "https://ftp.suse.com/pub/projects/security/osv/openSUSE-SU-2025:14873-1.json"
      },
      "ecosystem_specific": {
        "binaries": [
          {
            "python312": "3.12.9-2.1",
            "python312-32bit": "3.12.9-2.1",
            "python312-curses": "3.12.9-2.1",
            "python312-dbm": "3.12.9-2.1",
            "python312-idle": "3.12.9-2.1",
            "python312-tk": "3.12.9-2.1",
            "python312-x86-64-v3": "3.12.9-2.1"
          }
        ]
      },
      "package": {
        "ecosystem": "openSUSE:Tumbleweed",
        "name": "python312",
        "purl": "pkg:rpm/opensuse/python312&distro=openSUSE%20Tumbleweed"
      },
      "ranges": [
        {
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "3.12.9-2.1"
            }
          ],
          "type": "ECOSYSTEM"
        }
      ],
      "versions": []
    }
  ],
  "details": "These are all security issues fixed in the python312-3.12.9-2.1 package on the GA media of openSUSE Tumbleweed.",
  "id": "openSUSE-SU-2025:14873-1",
  "modified": "2025-05-07T18:16:39.806434Z",
  "published": "2025-03-11T00:00:00Z",
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://lists.opensuse.org/archives/list/security-announce@lists.opensuse.org/thread/5RE6ZQR3XPY6MB44SQS3SKCGBY3NJJKX/"
    },
    {
      "type": "WEB",
      "url": "https://www.suse.com/security/cve/CVE-2025-1795"
    }
  ],
  "related": [
    "CVE-2025-1795"
  ],
  "schema_version": "1.7.3",
  "summary": "python312-3.12.9-2.1 on GA media",
  "upstream": [
    "CVE-2025-1795"
  ]
}