{
  "affected": [
    {
      "database_specific": {
        "source": "https://ftp.suse.com/pub/projects/security/osv/openSUSE-SU-2024:10100-1.json"
      },
      "ecosystem_specific": {
        "binaries": [
          {
            "python3": "3.5.1-3.8",
            "python3-32bit": "3.5.1-3.8",
            "python3-curses": "3.5.1-3.8",
            "python3-dbm": "3.5.1-3.8",
            "python3-tk": "3.5.1-3.8"
          }
        ]
      },
      "package": {
        "ecosystem": "openSUSE:Tumbleweed",
        "name": "python3",
        "purl": "pkg:rpm/opensuse/python3&distro=openSUSE%20Tumbleweed"
      },
      "ranges": [
        {
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "3.5.1-3.8"
            }
          ],
          "type": "ECOSYSTEM"
        }
      ],
      "versions": []
    }
  ],
  "details": "These are all security issues fixed in the python3-3.5.1-3.8 package on the GA media of openSUSE Tumbleweed.",
  "id": "openSUSE-SU-2024:10100-1",
  "modified": "2025-05-07T18:08:53.938080Z",
  "published": "2024-06-15T00:00:00Z",
  "references": [
    {
      "type": "ADVISORY"
    },
    {
      "type": "WEB",
      "url": "https://www.suse.com/security/cve/CVE-2013-4238"
    },
    {
      "type": "WEB",
      "url": "https://www.suse.com/security/cve/CVE-2014-4650"
    }
  ],
  "related": [
    "CVE-2013-4238",
    "CVE-2014-4650"
  ],
  "schema_version": "1.6.0",
  "summary": "python3-3.5.1-3.8 on GA media",
  "upstream": [
    "CVE-2013-4238",
    "CVE-2014-4650"
  ]
}