{
  "affected": [
    {
      "database_specific": {
        "source": "https://security.access.redhat.com/data/osv/RHSA-2024:11238.json"
      },
      "package": {
        "ecosystem": "Red Hat:enterprise_linux:9::appstream",
        "name": "python3.11-urllib3",
        "purl": "pkg:rpm/redhat/python3.11-urllib3"
      },
      "ranges": [
        {
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "0:1.26.12-2.el9_5.2"
            }
          ],
          "type": "ECOSYSTEM"
        }
      ],
      "versions": []
    }
  ],
  "id": "RHSA-2024:11238",
  "modified": "2025-08-01T10:09:28Z",
  "published": "2024-12-18T10:06:08Z",
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://access.redhat.com/errata/RHSA-2024:11238"
    },
    {
      "type": "ARTICLE",
      "url": "https://access.redhat.com/security/updates/classification/#moderate"
    },
    {
      "type": "REPORT",
      "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2246840"
    },
    {
      "type": "ADVISORY",
      "url": "https://security.access.redhat.com/data/csaf/v2/advisories/2024/rhsa-2024_11238.json"
    },
    {
      "type": "REPORT",
      "url": "https://access.redhat.com/security/cve/CVE-2023-45803"
    },
    {
      "type": "ADVISORY",
      "url": "https://www.cve.org/CVERecord?id=CVE-2023-45803"
    },
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-45803"
    },
    {
      "type": "ARTICLE",
      "url": "https://github.com/urllib3/urllib3/commit/4e98d57809dacab1cbe625fddeec1a290c478ea9"
    },
    {
      "type": "ARTICLE",
      "url": "https://github.com/urllib3/urllib3/security/advisories/GHSA-g4mx-q9vg-27p4"
    },
    {
      "type": "ARTICLE",
      "url": "https://www.rfc-editor.org/rfc/rfc9110.html#name-get"
    }
  ],
  "schema_version": "1.7.0",
  "severity": [
    {
      "score": "CVSS:3.1/AV:A/AC:H/PR:H/UI:N/S:U/C:H/I:N/A:N",
      "type": "CVSS_V3"
    }
  ],
  "summary": "Red Hat Security Advisory: python3.11-urllib3 security update",
  "upstream": [
    "CVE-2023-45803"
  ]
}