{
  "affected": [
    {
      "database_specific": {
        "source": "https://github.com/canonical/ubuntu-security-notices/blob/main/osv/cve/2020/UBUNTU-CVE-2020-29657.json"
      },
      "package": {
        "ecosystem": "Ubuntu:Pro:18.04:LTS",
        "name": "iotjs",
        "purl": "pkg:deb/ubuntu/iotjs@1.0-1?arch=source&distro=esm-apps/bionic"
      },
      "ranges": [
        {
          "events": [
            {
              "introduced": "0"
            }
          ],
          "type": "ECOSYSTEM"
        }
      ],
      "versions": [
        "1.0-1"
      ]
    },
    {
      "database_specific": {
        "source": "https://github.com/canonical/ubuntu-security-notices/blob/main/osv/cve/2020/UBUNTU-CVE-2020-29657.json"
      },
      "package": {
        "ecosystem": "Ubuntu:22.04:LTS",
        "name": "iotjs",
        "purl": "pkg:deb/ubuntu/iotjs@1.0+715-1ubuntu2?arch=source&distro=jammy"
      },
      "ranges": [
        {
          "events": [
            {
              "introduced": "0"
            }
          ],
          "type": "ECOSYSTEM"
        }
      ],
      "versions": [
        "1.0+715-1ubuntu2"
      ]
    }
  ],
  "details": "In JerryScript 2.3.0, there is an out-of-bounds read in main_print_unhandled_exception in the main-utils.c file.",
  "id": "UBUNTU-CVE-2020-29657",
  "modified": "2025-07-16T07:41:32.946638Z",
  "published": "2020-12-09T09:15:00Z",
  "references": [
    {
      "type": "REPORT",
      "url": "https://ubuntu.com/security/CVE-2020-29657"
    },
    {
      "type": "REPORT",
      "url": "https://github.com/jerryscript-project/jerryscript/issues/4244"
    },
    {
      "type": "REPORT",
      "url": "https://www.cve.org/CVERecord?id=CVE-2020-29657"
    }
  ],
  "schema_version": "1.7.0",
  "severity": [
    {
      "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:H",
      "type": "CVSS_V3"
    },
    {
      "score": "medium",
      "type": "Ubuntu"
    }
  ],
  "upstream": [
    "CVE-2020-29657"
  ]
}